import type { Building, MapConfig } from './types';

export const DEFAULT_MAP_CONFIG: MapConfig = {
    cameraPosition: [15, 15, 15],
    cameraTarget: [0, 0, 0],
    zoomLevel: 1,
};

export const DEFAULT_BUILDINGS: Building[] = [
    {
        id: 'Building_Admin',
        name: 'Admin Building',
        description: 'Main administrative offices',
        position: [9.8, 0, -7.3],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Church',
        name: 'University Church',
        description: 'School chapel and religious services',
        position: [4.5, 0, 7.9],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Elementary',
        name: 'Elementary School',
        description: 'Elementary school building',
        position: [12.3, 0, -3.2],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Engineering',
        name: 'College of Engineering',
        description: 'Engineering and technology facilities',
        position: [-5, 0, 0],
        size: [0.7, 0.4, 0.7],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_EXCEL',
        name: 'EXCEL Building',
        description: 'EXCEL learning center',
        position: [7.1, 0, -4.7],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_FranklinHall',
        name: 'Franklin Hall',
        description: 'Academic building',
        position: [6.0, 0, -3.6],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_HSgym',
        name: 'High School Gym',
        description: 'High school gymnasium',
        position: [-1.1, 0, -7.8],
        size: [0.7, 0.4, 0.7],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_JohnsonHall',
        name: 'Johnson Hall',
        description: 'Residential hall',
        position: [10.5, 0, 3.0],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_JuniorHigh',
        name: 'Junior High School',
        description: 'Junior high school building',
        position: [2.2, 0, -6.4],
        size: [0.7, 0.35, 0.6],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Kindergarten',
        name: 'Kindergarten',
        description: 'Kindergarten building',
        position: [4.9, 0, 9.8],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_LDT',
        name: 'LDT Building',
        description: 'Learning development and training',
        position: [5.4, 0, 3.3],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_LEB',
        name: 'LEB Building',
        description: 'Laboratory and evaluation building',
        position: [5.0, 0, -10.4],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Library',
        name: 'Henry Luce Library',
        description: 'Main school library',
        position: [3.5, 0, 6.7],
        size: [0.6, 0.35, 0.6],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_LopezMemorial',
        name: 'Lopez Memorial',
        description: 'Memorial building',
        position: [6.3, 0, -10.0],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_MaryThomas',
        name: 'Mary Thomas Building',
        description: 'Academic building',
        position: [8.7, 0, -14.0],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_NewValentine',
        name: 'New Valentine',
        description: 'Valentine building (new)',
        position: [2.0, 0, -9.1],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_OldValentine',
        name: 'Old Valentine',
        description: 'Valentine building (old)',
        position: [1.0, 0, -12.0],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Packaging',
        name: 'Packaging Center',
        description: 'Packaging and logistics',
        position: [5.2, 0, -4.0],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Promenade',
        name: 'Promenade',
        description: 'Walkway and promenade area',
        position: [5.4, 0, -6.2],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Registrar',
        name: 'Registrar Office',
        description: 'Registrar building',
        position: [7.3, 0, 3.7],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Roblee',
        name: 'Roblee Hall',
        description: 'Academic hall',
        position: [0.0, 0, -6.7],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_RoseMemorial',
        name: 'Rose Memorial Auditorium',
        description: 'Main auditorium',
        position: [0.4, 0, 10.2],
        size: [0.6, 0.35, 0.6],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_SeniorHigh',
        name: 'Senior High School',
        description: 'Senior high school building',
        position: [4.1, 0, -11.3],
        size: [0.7, 0.4, 0.7],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_UniversityGym',
        name: 'University Gym',
        description: 'University gymnasium',
        position: [-2.0, 0, 14.5],
        size: [0.7, 0.4, 0.7],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_Uy',
        name: 'Uy Building',
        description: 'Academic building',
        position: [3.4, 0, -6.3],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
    {
        id: 'Building_WestonHall',
        name: 'Weston Hall',
        description: 'Residential and academic hall',
        position: [7.4, 0, -0.3],
        size: [0.5, 0.3, 0.5],
        rotation: 0,
        floors: [],
    },
];