/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\CentralMap.glb -o .\src\map\3d\CentralMapModel.tsx -k 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Building_Admin: THREE.Mesh
    Building_Background: THREE.Mesh
    Building_Church: THREE.Mesh
    Building_Elementary: THREE.Mesh
    Building_Engineering: THREE.Mesh
    Building_EXCEL: THREE.Mesh
    Building_FranklinHall: THREE.Mesh
    Building_HSgym: THREE.Mesh
    Building_JohnsonHall: THREE.Mesh
    Building_JuniorHigh: THREE.Mesh
    Building_Kindergarten: THREE.Mesh
    Building_LDT: THREE.Mesh
    Building_LEB: THREE.Mesh
    Building_Library: THREE.Mesh
    Building_LopezMemorial: THREE.Mesh
    Building_MaryThomas: THREE.Mesh
    Building_NewValentine: THREE.Mesh
    Building_OldValentine: THREE.Mesh
    Building_Packaging: THREE.Mesh
    Building_Promenade: THREE.Mesh
    Building_Registrar: THREE.Mesh
    Building_Roblee: THREE.Mesh
    Building_RoseMemorial: THREE.Mesh
    Building_SeniorHigh: THREE.Mesh
    Building_UniversityGym: THREE.Mesh
    Building_Uy: THREE.Mesh
    Building_WestonHall: THREE.Mesh
    Field_BigField: THREE.Mesh
    Field_HalfMoon: THREE.Mesh
    Field_SoftballField: THREE.Mesh
    Map_Floor: THREE.Mesh
    Map_Outline: THREE.Mesh
    Map_Roads: THREE.Mesh
  }
  materials: {
    grass: THREE.MeshStandardMaterial
    flooring: THREE.MeshStandardMaterial
    road: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CentralMap.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Empty" scale={11.523}>
        <mesh name="Building_Admin" geometry={nodes.Building_Admin.geometry} material={nodes.Building_Admin.material} position={[0.851, 0.004, -0.634]} scale={0.026} />
        <mesh name="Building_Background" geometry={nodes.Building_Background.geometry} material={nodes.Building_Background.material} position={[0.398, 0.004, 0.824]} scale={0.026} />
        <mesh name="Building_Church" geometry={nodes.Building_Church.geometry} material={nodes.Building_Church.material} position={[-0.483, 0.004, 0.689]} scale={0.026} />
        <mesh name="Building_Elementary" geometry={nodes.Building_Elementary.geometry} material={nodes.Building_Elementary.material} position={[1.066, 0.004, -0.277]} scale={0.026} />
        <mesh name="Building_Engineering" geometry={nodes.Building_Engineering.geometry} material={nodes.Building_Engineering.material} position={[-0.461, 0.004, -0.014]} scale={0.026} />
        <mesh name="Building_EXCEL" geometry={nodes.Building_EXCEL.geometry} material={nodes.Building_EXCEL.material} position={[0.62, 0.004, -0.407]} scale={0.026} />
        <mesh name="Building_FranklinHall" geometry={nodes.Building_FranklinHall.geometry} material={nodes.Building_FranklinHall.material} position={[-0.171, 0.004, -0.315]} scale={0.026} />
        <mesh name="Building_HSgym" geometry={nodes.Building_HSgym.geometry} material={nodes.Building_HSgym.material} position={[-0.873, 0.004, -0.682]} scale={0.026} />
        <mesh name="Building_JohnsonHall" geometry={nodes.Building_JohnsonHall.geometry} material={nodes.Building_JohnsonHall.material} position={[0.911, 0.004, 0.261]} scale={0.026} />
        <mesh name="Building_JuniorHigh" geometry={nodes.Building_JuniorHigh.geometry} material={nodes.Building_JuniorHigh.material} position={[-0.615, 0.004, -0.558]} scale={0.026} />
        <mesh name="Building_Kindergarten" geometry={nodes.Building_Kindergarten.geometry} material={nodes.Building_Kindergarten.material} position={[-0.422, 0.004, 0.855]} scale={0.026} />
        <mesh name="Building_LDT" geometry={nodes.Building_LDT.geometry} material={nodes.Building_LDT.material} position={[0.469, 0.004, 0.285]} scale={0.026} />
        <mesh name="Building_LEB" geometry={nodes.Building_LEB.geometry} material={nodes.Building_LEB.material} position={[-0.437, 0.004, -0.902]} scale={0.026} />
        <mesh name="Building_Library" geometry={nodes.Building_Library.geometry} material={nodes.Building_Library.material} position={[0.307, 0.004, 0.586]} scale={0.026} />
        <mesh name="Building_LopezMemorial" geometry={nodes.Building_LopezMemorial.geometry} material={nodes.Building_LopezMemorial.material} position={[-0.272, 0.004, -0.866]} scale={0.026} />
        <mesh name="Building_MaryThomas" geometry={nodes.Building_MaryThomas.geometry} material={nodes.Building_MaryThomas.material} position={[-0.1, 0.004, -1.212]} scale={0.026} />
        <mesh name="Building_NewValentine" geometry={nodes.Building_NewValentine.geometry} material={nodes.Building_NewValentine.material} position={[0.176, 0.004, -0.789]} scale={0.026} />
        <mesh name="Building_OldValentine" geometry={nodes.Building_OldValentine.geometry} material={nodes.Building_OldValentine.material} position={[0.083, 0.004, -1.046]} scale={0.026} />
        <mesh name="Building_Packaging" geometry={nodes.Building_Packaging.geometry} material={nodes.Building_Packaging.material} position={[-0.471, 0.004, -0.347]} scale={0.026} />
        <mesh name="Building_Promenade" geometry={nodes.Building_Promenade.geometry} material={nodes.Building_Promenade.material} position={[0.471, 0.004, -0.541]} scale={0.026} />
        <mesh name="Building_Registrar" geometry={nodes.Building_Registrar.geometry} material={nodes.Building_Registrar.material} position={[0.631, 0.004, 0.321]} scale={0.026} />
        <mesh name="Building_Roblee" geometry={nodes.Building_Roblee.geometry} material={nodes.Building_Roblee.material} position={[0.001, 0.004, -0.581]} scale={0.026} />
        <mesh name="Building_RoseMemorial" geometry={nodes.Building_RoseMemorial.geometry} material={nodes.Building_RoseMemorial.material} position={[0.039, 0.004, 0.888]} scale={0.026} />
        <mesh name="Building_SeniorHigh" geometry={nodes.Building_SeniorHigh.geometry} material={nodes.Building_SeniorHigh.material} position={[-0.643, 0.004, -0.98]} scale={0.026} />
        <mesh name="Building_UniversityGym" geometry={nodes.Building_UniversityGym.geometry} material={nodes.Building_UniversityGym.material} position={[-0.177, 0.004, 1.257]} scale={0.026} />
        <mesh name="Building_Uy" geometry={nodes.Building_Uy.geometry} material={nodes.Building_Uy.material} position={[-0.294, 0.004, -0.544]} scale={0.026} />
        <mesh name="Building_WestonHall" geometry={nodes.Building_WestonHall.geometry} material={nodes.Building_WestonHall.material} position={[0.643, 0.004, -0.029]} scale={0.026} />
        <mesh name="Field_BigField" geometry={nodes.Field_BigField.geometry} material={materials.grass} position={[-0.075, -0.016, 0.197]} scale={0.026} />
        <mesh name="Field_HalfMoon" geometry={nodes.Field_HalfMoon.geometry} material={materials.grass} position={[0.496, -0.016, -0.98]} scale={0.026} />
        <mesh name="Field_SoftballField" geometry={nodes.Field_SoftballField.geometry} material={materials.grass} position={[0.872, -0.016, 1.233]} scale={0.026} />
        <mesh name="Map_Floor" geometry={nodes.Map_Floor.geometry} material={materials.flooring} position={[-2.952, -0.05, 3.707]} scale={0.026} />
        <mesh name="Map_Outline" geometry={nodes.Map_Outline.geometry} material={nodes.Map_Outline.material} position={[-0.024, -0.05, 0.269]} scale={0.026} />
        <mesh name="Map_Roads" geometry={nodes.Map_Roads.geometry} material={materials.road} position={[0.434, -0.023, 0.332]} scale={0.026} />
      </group>
    </group>
  )
}

useGLTF.preload('/CentralMap.glb')
