
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Building_Admin: THREE.Mesh
    Building_Background: THREE.Mesh
    Building_Church: THREE.Mesh
    Building_Elementary: THREE.Mesh
    Building_Engineering: THREE.Mesh
    Building_EXCEL: THREE.Mesh
    Building_FranklinHall: THREE.Mesh
    Building_HSgym: THREE.Mesh
    Building_JohnsonHall: THREE.Mesh
    Building_JuniorHigh: THREE.Mesh
    Building_Kindergarten: THREE.Mesh
    Building_LDT: THREE.Mesh
    Building_LEB: THREE.Mesh
    Building_Library: THREE.Mesh
    Building_LopezMemorial: THREE.Mesh
    Building_MaryThomas: THREE.Mesh
    Building_NewValentine: THREE.Mesh
    Building_OldValentine: THREE.Mesh
    Building_Packaging: THREE.Mesh
    Building_Promenade: THREE.Mesh
    Building_Registrar: THREE.Mesh
    Building_Roblee: THREE.Mesh
    Building_RoseMemorial: THREE.Mesh
    Building_SeniorHigh: THREE.Mesh
    Building_UniversityGym: THREE.Mesh
    Building_Uy: THREE.Mesh
    Building_WestonHall: THREE.Mesh
    Field_BigField: THREE.Mesh
    Field_HalfMoon: THREE.Mesh
    Field_SoftballField: THREE.Mesh
    Map_Floor: THREE.Mesh
    Map_Outline: THREE.Mesh
    Map_Roads: THREE.Mesh
  }
  materials: {
    grass: THREE.MeshStandardMaterial
    flooring: THREE.MeshStandardMaterial
    road: THREE.MeshStandardMaterial
  }
}

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/CentralMap.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      BuildingAdmin: nodes.Building_Admin,
      BuildingBackground: nodes.Building_Background,
      BuildingChurch: nodes.Building_Church,
      BuildingElementary: nodes.Building_Elementary,
      BuildingEngineering: nodes.Building_Engineering,
      BuildingEXCEL: nodes.Building_EXCEL,
      BuildingFranklinHall: nodes.Building_FranklinHall,
      BuildingHSgym: nodes.Building_HSgym,
      BuildingJohnsonHall: nodes.Building_JohnsonHall,
      BuildingJuniorHigh: nodes.Building_JuniorHigh,
      BuildingKindergarten: nodes.Building_Kindergarten,
      BuildingLDT: nodes.Building_LDT,
      BuildingLEB: nodes.Building_LEB,
      BuildingLibrary: nodes.Building_Library,
      BuildingLopezMemorial: nodes.Building_LopezMemorial,
      BuildingMaryThomas: nodes.Building_MaryThomas,
      BuildingNewValentine: nodes.Building_NewValentine,
      BuildingOldValentine: nodes.Building_OldValentine,
      BuildingPackaging: nodes.Building_Packaging,
      BuildingPromenade: nodes.Building_Promenade,
      BuildingRegistrar: nodes.Building_Registrar,
      BuildingRoblee: nodes.Building_Roblee,
      BuildingRoseMemorial: nodes.Building_RoseMemorial,
      BuildingSeniorHigh: nodes.Building_SeniorHigh,
      BuildingUniversityGym: nodes.Building_UniversityGym,
      BuildingUy: nodes.Building_Uy,
      BuildingWestonHall: nodes.Building_WestonHall,
      FieldBigField: nodes.Field_BigField,
      FieldHalfMoon: nodes.Field_HalfMoon,
      FieldSoftballField: nodes.Field_SoftballField,
      MapFloor: nodes.Map_Floor,
      MapOutline: nodes.Map_Outline,
      MapRoads: nodes.Map_Roads,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" scale={11.523} userData={{ name: 'Empty' }}>
          <instances.BuildingAdmin
            name="Building_Admin"
            position={[0.851, 0.004, -0.634]}
            scale={0.026}
            userData={{ name: 'Building_Admin' }}
          />
          <instances.BuildingBackground
            name="Building_Background"
            position={[0.398, 0.004, 0.824]}
            scale={0.026}
            userData={{ name: 'Building_Background' }}
          />
          <instances.BuildingChurch
            name="Building_Church"
            position={[-0.483, 0.004, 0.689]}
            scale={0.026}
            userData={{ name: 'Building_Church' }}
          />
          <instances.BuildingElementary
            name="Building_Elementary"
            position={[1.066, 0.004, -0.277]}
            scale={0.026}
            userData={{ name: 'Building_Elementary' }}
          />
          <instances.BuildingEngineering
            name="Building_Engineering"
            position={[-0.461, 0.004, -0.014]}
            scale={0.026}
            userData={{ name: 'Building_Engineering' }}
          />
          <instances.BuildingEXCEL
            name="Building_EXCEL"
            position={[0.62, 0.004, -0.407]}
            scale={0.026}
            userData={{ name: 'Building_EXCEL' }}
          />
          <instances.BuildingFranklinHall
            name="Building_FranklinHall"
            position={[-0.171, 0.004, -0.315]}
            scale={0.026}
            userData={{ name: 'Building_FranklinHall' }}
          />
          <instances.BuildingHSgym
            name="Building_HSgym"
            position={[-0.873, 0.004, -0.682]}
            scale={0.026}
            userData={{ name: 'Building_HSgym' }}
          />
          <instances.BuildingJohnsonHall
            name="Building_JohnsonHall"
            position={[0.911, 0.004, 0.261]}
            scale={0.026}
            userData={{ name: 'Building_JohnsonHall' }}
          />
          <instances.BuildingJuniorHigh
            name="Building_JuniorHigh"
            position={[-0.615, 0.004, -0.558]}
            scale={0.026}
            userData={{ name: 'Building_JuniorHigh' }}
          />
          <instances.BuildingKindergarten
            name="Building_Kindergarten"
            position={[-0.422, 0.004, 0.855]}
            scale={0.026}
            userData={{ name: 'Building_Kindergarten' }}
          />
          <instances.BuildingLDT
            name="Building_LDT"
            position={[0.469, 0.004, 0.285]}
            scale={0.026}
            userData={{ name: 'Building_LDT' }}
          />
          <instances.BuildingLEB
            name="Building_LEB"
            position={[-0.437, 0.004, -0.902]}
            scale={0.026}
            userData={{ name: 'Building_LEB' }}
          />
          <instances.BuildingLibrary
            name="Building_Library"
            position={[0.307, 0.004, 0.586]}
            scale={0.026}
            userData={{ name: 'Building_Library' }}
          />
          <instances.BuildingLopezMemorial
            name="Building_LopezMemorial"
            position={[-0.272, 0.004, -0.866]}
            scale={0.026}
            userData={{ name: 'Building_LopezMemorial' }}
          />
          <instances.BuildingMaryThomas
            name="Building_MaryThomas"
            position={[-0.1, 0.004, -1.212]}
            scale={0.026}
            userData={{ name: 'Building_MaryThomas' }}
          />
          <instances.BuildingNewValentine
            name="Building_NewValentine"
            position={[0.176, 0.004, -0.789]}
            scale={0.026}
            userData={{ name: 'Building_NewValentine' }}
          />
          <instances.BuildingOldValentine
            name="Building_OldValentine"
            position={[0.083, 0.004, -1.046]}
            scale={0.026}
            userData={{ name: 'Building_OldValentine' }}
          />
          <instances.BuildingPackaging
            name="Building_Packaging"
            position={[-0.471, 0.004, -0.347]}
            scale={0.026}
            userData={{ name: 'Building_Packaging' }}
          />
          <instances.BuildingPromenade
            name="Building_Promenade"
            position={[0.471, 0.004, -0.541]}
            scale={0.026}
            userData={{ name: 'Building_Promenade' }}
          />
          <instances.BuildingRegistrar
            name="Building_Registrar"
            position={[0.631, 0.004, 0.321]}
            scale={0.026}
            userData={{ name: 'Building_Registrar' }}
          />
          <instances.BuildingRoblee
            name="Building_Roblee"
            position={[0.001, 0.004, -0.581]}
            scale={0.026}
            userData={{ name: 'Building_Roblee' }}
          />
          <instances.BuildingRoseMemorial
            name="Building_RoseMemorial"
            position={[0.039, 0.004, 0.888]}
            scale={0.026}
            userData={{ name: 'Building_RoseMemorial' }}
          />
          <instances.BuildingSeniorHigh
            name="Building_SeniorHigh"
            position={[-0.643, 0.004, -0.98]}
            scale={0.026}
            userData={{ name: 'Building_SeniorHigh' }}
          />
          <instances.BuildingUniversityGym
            name="Building_UniversityGym"
            position={[-0.177, 0.004, 1.257]}
            scale={0.026}
            userData={{ name: 'Building_UniversityGym' }}
          />
          <instances.BuildingUy
            name="Building_Uy"
            position={[-0.294, 0.004, -0.544]}
            scale={0.026}
            userData={{ name: 'Building_Uy' }}
          />
          <instances.BuildingWestonHall
            name="Building_WestonHall"
            position={[0.643, 0.004, -0.029]}
            scale={0.026}
            userData={{ name: 'Building_WestonHall' }}
          />
          <instances.FieldBigField
            name="Field_BigField"
            position={[-0.075, -0.016, 0.197]}
            scale={0.026}
            userData={{ name: 'Field_BigField' }}
          />
          <instances.FieldHalfMoon
            name="Field_HalfMoon"
            position={[0.496, -0.016, -0.98]}
            scale={0.026}
            userData={{ name: 'Field_HalfMoon' }}
          />
          <instances.FieldSoftballField
            name="Field_SoftballField"
            position={[0.872, -0.016, 1.233]}
            scale={0.026}
            userData={{ name: 'Field_SoftballField' }}
          />
          <instances.MapFloor
            name="Map_Floor"
            position={[-2.952, -0.05, 3.707]}
            scale={0.026}
            userData={{ name: 'Map_Floor' }}
          />
          <instances.MapOutline
            name="Map_Outline"
            position={[-0.024, -0.05, 0.269]}
            scale={0.026}
            userData={{ name: 'Map_Outline' }}
          />
          <instances.MapRoads
            name="Map_Roads"
            position={[0.434, -0.023, 0.332]}
            scale={0.026}
            userData={{ name: 'Map_Roads' }}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/CentralMap.glb')
